[versions]
konsist = "0.17.3"
kotest = "6.1.11"
kotlin = "2.3.21"
ksp = "2.3.7"
spotless = "8.5.1"

[plugins]
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
